config/routes.rb
FlailsToRails::Application.routes.draw do
  resources :entries do
    resources :comments
  end

  root :to => 'entries#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :entry

  attr_accessible :body, :email

  validates_presence_of :body, :email
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  has_many :comments

  attr_accessible :email, :title, :url

  validates_presence_of :url, :email

  def self.most_recent_first
    order('created_at DESC')
  end

  def new_comment(params = {})
    comment = Comment.new(params)
    comment.entry = self
    comment
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @entry = Entry.find(params[:entry_id])
    @comments = @entry.comments
    @new_comment = @entry.new_comment
  end

  def create
    @entry = Entry.find(params[:entry_id])
    @new_comment = @entry.new_comment(params[:comment])

    if @new_comment.save
      flash[:success] = "Your comment was submitted successfully."
      redirect_to entry_comments_path(@entry)
    else
      @comments = @entry.comments
      render :index
    end
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @entries = Entry.most_recent_first.page(params[:page])
  end

  def new
    @entry = Entry.new
  end

  def create
    @entry = Entry.new(params[:entry])
    if @entry.save
      flash[:success] = "Your entry was submitted successfully."
      redirect_to entries_path
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def navbar_item(title, path)
    klass = request.path == path ? 'active' : nil
    content_tag :li, :class => klass do
      link_to title, path
    end
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
  def comments_link_for_entry(entry)
    link_to pluralize(entry.comments.count, "comment"), entry_comments_path(entry)
  end
end

app/views/comments/_comment.html.erb
<div class="comment">
  <p>
    <span class="gravatar gravatar-small"><%= gravatar_image_tag(comment.email, :gravatar => { :size => 30 }) %></span>
    <strong><%= comment.email %></strong> said <%= time_ago_in_words(comment.created_at) %> ago:<br/>
    <%= comment.body %>
  </p>
</div>

app/views/comments/_form.html.erb
<%= render 'shared/error_messages', :target => comment %>
<%= form_for [entry, comment] do |f| %>
  <div>
    <%= f.text_area :body, :class => 'input-xlarge', :rows => 4 %>
  </div>
  <div>
    <%= f.label :email, "Your email:" %><%= f.text_field :email, :class => 'input-xlarge', :placeholder => "user@example.com" %>
  </div>
  <div>
    <%= f.submit "Add Comment", :class => 'btn' %>
  </div>
<% end %>

app/views/comments/index.html.erb
<div id="entry-summary">
  <h1><%= link_to @entry.title, @entry.url %></h1>
  <p class="metadata">
    Submitted <%= time_ago_in_words(@entry.created_at) %> ago by <%= @entry.email %>
  </p>
</div>

<div id="comments">
  <h2>Comments</h2>

  <%= render 'form', :entry => @entry, :comment => @new_comment %>

  <% if @comments.empty? %>
    <p>No one has commented on this yet.</p>
  <% else %>
    <% @comments.each do |comment| %>
      <%= render comment %>
    <% end %>
  <% end %>
</div>

app/views/entries/_entry.html.erb
<div class="entry row-fluid">
  <div class="well span12">
    <div class="gravatar">
      <%= gravatar_image_tag(entry.email) %>
    </div>
    <h2 class="title">
      <%= link_to entry.title, entry.url %>
    </h2>
    <p class="metadata">
      Submitted <%= time_ago_in_words(entry.created_at) %> ago by <%= entry.email %><br/>
      <%= comments_link_for_entry(entry) %>
    </p>
  </div>
</div>

app/views/entries/index.html.erb
<% if @entries.empty? %>
  <div class="alert alert-block alert-info">
    <h4 class="alert-warning">There is nothing here :(</h4>
    Maybe you could <%= link_to "submit an entry", new_entry_path %> to liven up the place.
  </div>
<% else %>
  <% @entries.each do |entry| %>
    <%= render entry %>
  <% end %>
<% end %>

<%= paginate @entries %>

app/views/entries/new.html.erb
<%= render 'shared/error_messages', :target => @entry %>
<%= form_for @entry, :html => { :class => 'well form-horizontal' } do |f| %>
  <fieldset>
    <div class="control-group">
      <%= f.label :url, "URL", :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :url, :placeholder => "http://www.example.com", :class => 'span5' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :title, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :title, :placeholder => "Enter a title for your submission", :class => 'span5' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :email, "Your email", :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :email, :placeholder => "user@example.com" %>
      </div>
    </div>
    <div class="control-group">
      <div class="controls">
        <%= f.submit :class => 'btn' %>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flails to Rails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar">
    <%= render 'shared/navbar' %>
  </div>

  <div class="container-fluid">
    <%= render 'shared/flashes' %>
    <%= yield %>
  </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
  <div class="alert alert-block alert-error">
    <h4 class="alert-heading">Validation failed</h4>
    <%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:
    <ul>
      <% target.errors.full_messages.each do |msg| %>
        <%= content_tag :li, msg %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% flash.each do |key, msg| %>
  <%= content_tag :div, :class => "alert alert-#{key}" do %>
    <a class="close" data-dismiss="alert" href="#">x</a>
    <%= msg %>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-inner">
  <div class="container">
    <%= link_to "Flails to Rails", root_path, :class => 'brand' %>
    <ul class="nav">
      <%= navbar_item "Submit an entry", new_entry_path %>
    </ul>
  </div>
</div>